apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 10901
      targetPort: 10901
---
{{- if eq .thanos.mode "client"}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: thanos-sidecar
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: "{{.thanos.thanosSidecarEndpoint}}"
    http:
      paths:
      - backend:
          serviceName: thanos-sidecar
          servicePort: 10901
{{- end}}          
